sudo: required
services:
    - docker

before_install:
    - docker build -t ashar/dockerreact -f Dockerfile.dev .

script:
      - docker run -e CI=true ashar/dockerreact npm run test


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dcoker-react"
    env: "DcokerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-980874804229"
    bucket_path: "dcoker-react"
    on:
        branch: master
    access_key_id: $Aws_Access_key
    secret_access_key:
        secure: "$Aws_Secret_key"


    
